services:
  label-scraper:
    build:
      target: production
    volumes:
      - ./output:/app/output/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    restart: unless-stopped
    command: npm start
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 128M