services:
  label-scraper:
    build:
      target: production
      tags:
        - registry.gitlab.com/gena.bondarev/token_back/label-scraper:latest
    volumes:
      - ./output:/app/output/
    env_file:
      - .env
    restart: always
    command: npm start
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 128M